# This is copied from
# https://stat.ink/api/v3/ability?full=1
# noinspection SpellCheckingInspection
ABILITY_DATA = [
    {
        "key": "ink_saver_main",
        "name": {
            "de_DE": "Hauptverbrauch",
            "en_GB": "Ink Saver (Main)",
            "en_US": "Ink Saver (Main)",
            "es_ES": "Tintahorro (ppal.)",
            "es_MX": "Ahorro tinta (ppal.)",
            "fr_CA": "Encrémenteur (pr.)",
            "fr_FR": "Encrémenteur (pr.)",
            "it_IT": "Eco-colore princ.",
            "ja_JP": "インク効率アップ(メイン)",
            "ko_KR": "잉크 효율 업(메인)",
            "nl_NL": "Hoofdspaarder",
            "ru_RU": "Основной баллон X",
            "zh_CN": "提升墨汁效率（主要武器）",
            "zh_TW": "提升墨汁效率（主要武器）",
        },
        "primary_only": False,
    },
    {
        "key": "ink_saver_sub",
        "name": {
            "de_DE": "Sekundärverbrauch",
            "en_GB": "Ink Saver (Sub)",
            "en_US": "Ink Saver (Sub)",
            "es_ES": "Tintahorro (sec.)",
            "es_MX": "Ahorro tinta (sec.)",
            "fr_CA": "Encrémenteur (sec.)",
            "fr_FR": "Encrémenteur (sec.)",
            "it_IT": "Eco-colore second.",
            "ja_JP": "インク効率アップ(サブ)",
            "ko_KR": "잉크 효율 업(서브)",
            "nl_NL": "Subspaarder",
            "ru_RU": "Запасной баллон X",
            "zh_CN": "提升墨汁效率（次要武器）",
            "zh_TW": "提升墨汁效率（次要武器）",
        },
        "primary_only": False,
    },
    {
        "key": "ink_recovery_up",
        "name": {
            "de_DE": "Regeneration +",
            "en_GB": "Ink Recovery Up",
            "en_US": "Ink Recovery Up",
            "es_ES": "Recarga rápida",
            "es_MX": "Mejor recarga tinta",
            "fr_CA": "Levée d'encre",
            "fr_FR": "Levée d'encre",
            "it_IT": "Recupero colore +",
            "ja_JP": "インク回復力アップ",
            "ko_KR": "잉크 회복력 업",
            "nl_NL": "Inktvulling",
            "ru_RU": "Быстрый баллон",
            "zh_CN": "提升墨汁回复力",
            "zh_TW": "提升墨汁回復力",
        },
        "primary_only": False,
    },
    {
        "key": "run_speed_up",
        "name": {
            "de_DE": "Lauftempo +",
            "en_GB": "Run Speed Up",
            "en_US": "Run Speed Up",
            "es_ES": "Supercarrera",
            "es_MX": "Carrera acelerada",
            "fr_CA": "Course à pied",
            "fr_FR": "Course à pied",
            "it_IT": "Velocità +",
            "ja_JP": "ヒト移動速度アップ",
            "ko_KR": "인간 이동 속도 업",
            "nl_NL": "Hardloper",
            "ru_RU": "Спринтер",
            "zh_CN": "提升人类移动速度",
            "zh_TW": "提升人類移動速度",
        },
        "primary_only": False,
    },
    {
        "key": "swim_speed_up",
        "name": {
            "de_DE": "Schwimmtempo +",
            "en_GB": "Swim Speed Up",
            "en_US": "Swim Speed Up",
            "es_ES": "Superbuceo",
            "es_MX": "Nado acelerado",
            "fr_CA": "Turbo-calmar",
            "fr_FR": "Turbo-calamar",
            "it_IT": "Velocità nuoto +",
            "ja_JP": "イカダッシュ速度アップ",
            "ko_KR": "징어대시 속도 업",
            "nl_NL": "Zwemdiploma",
            "ru_RU": "Плавунец",
            "zh_CN": "提升鱿鱼冲刺速度",
            "zh_TW": "提升魷魚衝刺速度",
        },
        "primary_only": False,
    },
    {
        "key": "special_charge_up",
        "name": {
            "de_DE": "Spezialladezeit +",
            "en_GB": "Special Charge Up",
            "en_US": "Special Charge Up",
            "es_ES": "Recarga especial",
            "es_MX": "Recarga especial",
            "fr_CA": "Jauge spéciale +",
            "fr_FR": "Jauge spéciale +",
            "it_IT": "Ricarica speciale +",
            "ja_JP": "スペシャル増加量アップ",
            "ko_KR": "스페셜 증가량 업",
            "nl_NL": "Speciaallader",
            "ru_RU": "Особый насос",
            "zh_CN": "提升特殊武器增加量",
            "zh_TW": "提升特殊武器增加量",
        },
        "primary_only": False,
    },
    {
        "key": "special_saver",
        "name": {
            "de_DE": "Spezialabzug -",
            "en_GB": "Special Saver",
            "en_US": "Special Saver",
            "es_ES": "Reducción especial",
            "es_MX": "Ahorro especial",
            "fr_CA": "Baisse spéciale -",
            "fr_FR": "Baisse spéciale -",
            "it_IT": "Riduzione speciale -",
            "ja_JP": "スペシャル減少量ダウン",
            "ko_KR": "스페셜 감소량 다운",
            "nl_NL": "Speciaalspaarder",
            "ru_RU": "Особый резерв",
            "zh_CN": "降低特殊武器减少量",
            "zh_TW": "降低特殊武器減少量",
        },
        "primary_only": False,
    },
    {
        "key": "special_power_up",
        "name": {
            "de_DE": "Spezialstärke +",
            "en_GB": "Special Power Up",
            "en_US": "Special Power Up",
            "es_ES": "Superarma especial",
            "es_MX": "Mejora especial",
            "fr_CA": "Arme spéciale +",
            "fr_FR": "Arme spéciale +",
            "it_IT": "Arma speciale +",
            "ja_JP": "スペシャル性能アップ",
            "ko_KR": "스페셜 성능 업",
            "nl_NL": "Specialist",
            "ru_RU": "Особый подход",
            "zh_CN": "提升特殊武器性能",
            "zh_TW": "提升特殊武器性能",
        },
        "primary_only": False,
    },
    {
        "key": "quick_respawn",
        "name": {
            "de_DE": "Schnelle Rückkehr",
            "en_GB": "Quick Respawn",
            "en_US": "Quick Respawn",
            "es_ES": "Retorno exprés",
            "es_MX": "Regeneración rápida",
            "fr_CA": "Sans temps mort",
            "fr_FR": "Sans temps morts",
            "it_IT": "Il tempo è colore",
            "ja_JP": "復活時間短縮",
            "ko_KR": "부활 시간 단축",
            "nl_NL": "Comeback",
            "ru_RU": "Феникс",
            "zh_CN": "缩短复活时间",
            "zh_TW": "縮短復活時間",
        },
        "primary_only": False,
    },
    {
        "key": "quick_super_jump",
        "name": {
            "de_DE": "Supersprung +",
            "en_GB": "Quick Super Jump",
            "en_US": "Quick Super Jump",
            "es_ES": "Supersalto rápido",
            "es_MX": "Supersalto rápido",
            "fr_CA": "Aérodynamisme",
            "fr_FR": "Aérodynamisme",
            "it_IT": "Salti super e veloci",
            "ja_JP": "スーパージャンプ時間短縮",
            "ko_KR": "슈퍼 점프 시간 단축",
            "nl_NL": "Turbosprong",
            "ru_RU": "Суперпрыгун",
            "zh_CN": "缩短超级跳跃时间",
            "zh_TW": "縮短超級跳躍時間",
        },
        "primary_only": False,
    },
    {
        "key": "sub_power_up",
        "name": {
            "de_DE": "Sekundärstärke +",
            "en_GB": "Sub Power Up",
            "en_US": "Sub Power Up",
            "es_ES": "Superarma secundaria",
            "es_MX": "Mejora secundaria",
            "fr_CA": "Arme secondaire +",
            "fr_FR": "Arme secondaire +",
            "it_IT": "Arma secondaria +",
            "ja_JP": "サブ性能アップ",
            "ko_KR": "서브 성능 업",
            "nl_NL": "Subtopper",
            "ru_RU": "Про-Запас",
            "zh_CN": "提升次要武器性能",
            "zh_TW": "提升次要武器性能",
        },
        "primary_only": False,
    },
    {
        "key": "ink_resistance_up",
        "name": {
            "de_DE": "Tintentoleranz +",
            "en_GB": "Ink Resistance Up",
            "en_US": "Ink Resistance Up",
            "es_ES": "Impermeabilidad",
            "es_MX": "Impermeabilidad",
            "fr_CA": "Imperméabilité",
            "fr_FR": "Pieds au sec",
            "it_IT": "Scarpe impermeabili",
            "ja_JP": "相手インク影響軽減",
            "ko_KR": "상대 잉크 영향 감소",
            "nl_NL": "Inkttolerantie",
            "ru_RU": "Краскостойкость",
            "zh_CN": "减轻对手墨汁影响",
            "zh_TW": "減輕對手墨汁影響",
        },
        "primary_only": False,
    },
    {
        "key": "sub_resistance_up",
        "name": {
            "de_DE": "Sekundärschutz +",
            "en_GB": "Sub Resistance Up",
            "en_US": "Sub Resistance Up",
            "es_ES": "Resistencia secundaria",
            "es_MX": "Resistencia secundaria",
            "fr_CA": "Filtre à secondaires",
            "fr_FR": "Filtre à secondaires",
            "it_IT": "Arma sec. impermeabile",
            "ja_JP": "サブ影響軽減",
            "ko_KR": "서브 영향 감소",
            "nl_NL": "Subdemper",
            "ru_RU": "Стойкость запаса",
            "zh_CN": "减轻次要武器影响",
            "zh_TW": "減輕次要武器影響",
        },
        "primary_only": False,
    },
    {
        "key": "intensify_action",
        "name": {
            "de_DE": "Action +",
            "en_GB": "Intensify Action",
            "en_US": "Intensify Action",
            "es_ES": "Agilidad extra",
            "es_MX": "Agilidad extra",
            "fr_CA": "Feu de l'action",
            "fr_FR": "Feu de l'action",
            "it_IT": "Intensificazione",
            "ja_JP": "アクション強化",
            "ko_KR": "액션 강화",
            "nl_NL": "Actie-assistentie",
            "ru_RU": "Ультраудар",
            "zh_CN": "行动强化",
            "zh_TW": "行動強化",
        },
        "primary_only": False,
    },
    {
        "key": "opening_gambit",
        "name": {
            "de_DE": "Startvorteil",
            "en_GB": "Opening Gambit",
            "en_US": "Opening Gambit",
            "es_ES": "Acelerón de salida",
            "es_MX": "Acelerón de salida",
            "fr_CA": "Départ toute allure",
            "fr_FR": "Chapeaux de roue",
            "it_IT": "Partenza a razzo",
            "ja_JP": "スタートダッシュ",
            "ko_KR": "스타트 대시",
            "nl_NL": "Vliegende start",
            "ru_RU": "Стартовый спурт",
            "zh_CN": "最初冲刺",
            "zh_TW": "最初衝刺",
        },
        "primary_only": True,
    },
    {
        "key": "last_ditch_effort",
        "name": {
            "de_DE": "Endspurt",
            "en_GB": "Last-Ditch Effort",
            "en_US": "Last-Ditch Effort",
            "es_ES": "Sprint Final",
            "es_MX": "Último recurso",
            "fr_CA": "Ultime sursaut",
            "fr_FR": "Ultime sursaut",
            "it_IT": "Slash finale",
            "ja_JP": "ラストスパート",
            "ko_KR": "라스트 스퍼트",
            "nl_NL": "Eindsprint",
            "ru_RU": "Финишный спурт",
            "zh_CN": "最后冲刺",
            "zh_TW": "最後衝刺",
        },
        "primary_only": True,
    },
    {
        "key": "tenacity",
        "name": {
            "de_DE": "Zähigkeit",
            "en_GB": "Tenacity",
            "en_US": "Tenacity",
            "es_ES": "Ventaja",
            "es_MX": "Tenacidad",
            "fr_CA": "Ténacité",
            "fr_FR": "Justice",
            "it_IT": "Tenacia",
            "ja_JP": "逆境強化",
            "ko_KR": "역경 강화",
            "nl_NL": "Volharding",
            "ru_RU": "Компенсатор",
            "zh_CN": "逆境强化",
            "zh_TW": "逆境強化",
        },
        "primary_only": True,
    },
    {
        "key": "comeback",
        "name": {
            "de_DE": "Rückkehr",
            "en_GB": "Comeback",
            "en_US": "Comeback",
            "es_ES": "Remontada",
            "es_MX": "Remonte",
            "fr_CA": "Retour",
            "fr_FR": "Come-back",
            "it_IT": "Gran ritorno",
            "ja_JP": "カムバック",
            "ko_KR": "컴백",
            "nl_NL": "Opfrisser",
            "ru_RU": "Ответный удар",
            "zh_CN": "回归",
            "zh_TW": "回歸",
        },
        "primary_only": True,
    },
    {
        "key": "ninja_squid",
        "name": {
            "de_DE": "Tintenfisch-Ninja",
            "en_GB": "Ninja Squid",
            "en_US": "Ninja Squid",
            "es_ES": "Ninjalamar",
            "es_MX": "Ninjalamar",
            "fr_CA": "Ninjalmar",
            "fr_FR": "Ninjalamar",
            "it_IT": "Calamaro ninja",
            "ja_JP": "イカニンジャ",
            "ko_KR": "징어닌자",
            "nl_NL": "Ninja-inktvis",
            "ru_RU": "Мимикрия",
            "zh_CN": "鱿鱼忍者",
            "zh_TW": "魷魚忍者",
        },
        "primary_only": True,
    },
    {
        "key": "haunt",
        "name": {
            "de_DE": "Vergeltung",
            "en_GB": "Haunt",
            "en_US": "Haunt",
            "es_ES": "Represalia",
            "es_MX": "Resentimiento",
            "fr_CA": "Vengeance",
            "fr_FR": "Revanche",
            "it_IT": "Rappresaglia",
            "ja_JP": "リベンジ",
            "ko_KR": "리벤지",
            "nl_NL": "Revanche",
            "ru_RU": "Вендетта",
            "zh_CN": "复仇",
            "zh_TW": "復仇",
        },
        "primary_only": True,
    },
    {
        "key": "thermal_ink",
        "name": {
            "de_DE": "Markierfarbe",
            "en_GB": "Thermal Ink",
            "en_US": "Thermal Ink",
            "es_ES": "Señuelo",
            "es_MX": "Tinta rastreadora",
            "fr_CA": "Encre thermique",
            "fr_FR": "Encre thermique",
            "it_IT": "Inchiostro termico",
            "ja_JP": "サーマルインク",
            "ko_KR": "서멀 잉크",
            "nl_NL": "Markeerstift",
            "ru_RU": "Клеймо",
            "zh_CN": "热力墨汁",
            "zh_TW": "熱力墨汁",
        },
        "primary_only": True,
    },
    {
        "key": "respawn_punisher",
        "name": {
            "de_DE": "Heimsuchung",
            "en_GB": "Respawn Punisher",
            "en_US": "Respawn Punisher",
            "es_ES": "Castigo póstumo",
            "es_MX": "Castigo póstumo",
            "fr_CA": "Retour perdant",
            "fr_FR": "Retour perdant",
            "it_IT": "Castigo",
            "ja_JP": "復活ペナルティアップ",
            "ko_KR": "부활 페널티 업",
            "nl_NL": "Repercussie",
            "ru_RU": "Кара",
            "zh_CN": "提升复活惩罚",
            "zh_TW": "提升復活懲罰",
        },
        "primary_only": True,
    },
    {
        "key": "ability_doubler",
        "name": {
            "de_DE": "Effektdoppelung",
            "en_GB": "Ability Doubler",
            "en_US": "Ability Doubler",
            "es_ES": "Duplicador",
            "es_MX": "Duplicador",
            "fr_CA": "Bonus ×2",
            "fr_FR": "Bonus ×2",
            "it_IT": "Raddoppiatore",
            "ja_JP": "追加ギアパワー倍化",
            "ko_KR": "추가 기어 파워 2배",
            "nl_NL": "Verdubbelaar",
            "ru_RU": "Дупликатор",
            "zh_CN": "追加装备能力增倍",
            "zh_TW": "追加裝備能力增倍",
        },
        "primary_only": True,
    },
    {
        "key": "stealth_jump",
        "name": {
            "de_DE": "Sprunginfiltration",
            "en_GB": "Stealth Jump",
            "en_US": "Stealth Jump",
            "es_ES": "Supersalto invisible",
            "es_MX": "Supersalto invisible",
            "fr_CA": "Super saut invisible",
            "fr_FR": "Réception réussie",
            "it_IT": "Salto al buio",
            "ja_JP": "ステルスジャンプ",
            "ko_KR": "스텔스 점프",
            "nl_NL": "Sluipsprong",
            "ru_RU": "Десант",
            "zh_CN": "隐身跳跃",
            "zh_TW": "隱身跳躍",
        },
        "primary_only": True,
    },
    {
        "key": "object_shredder",
        "name": {
            "de_DE": "Zerstörer",
            "en_GB": "Object Shredder",
            "en_US": "Object Shredder",
            "es_ES": "Demolición",
            "es_MX": "Demolición",
            "fr_CA": "Démolition",
            "fr_FR": "Démolition",
            "it_IT": "Demolitore",
            "ja_JP": "対物攻撃力アップ",
            "ko_KR": "오브젝트 공격력 업",
            "nl_NL": "Sloper",
            "ru_RU": "Демонтажник",
            "zh_CN": "提升对物体攻击力",
            "zh_TW": "提升對物體攻擊力",
        },
        "primary_only": True,
    },
    {
        "key": "drop_roller",
        "name": {
            "de_DE": "Tricklandung",
            "en_GB": "Drop Roller",
            "en_US": "Drop Roller",
            "es_ES": "Amortiguador",
            "es_MX": "Aterrizaje rodante",
            "fr_CA": "Super roulade",
            "fr_FR": "Super roulade",
            "it_IT": "Atterraggio stiloso",
            "ja_JP": "受け身術",
            "ko_KR": "낙법",
            "nl_NL": "Rolmodel",
            "ru_RU": "Акробат",
            "zh_CN": "受身术",
            "zh_TW": "受身術",
        },
        "primary_only": True,
    },
]
